// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// poppler_info
List poppler_info();
RcppExport SEXP pdftools_poppler_info() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(poppler_info());
    return __result;
END_RCPP
}
// poppler_pdf_info
List poppler_pdf_info(RawVector x, std::string owner_password, std::string user_password);
RcppExport SEXP pdftools_poppler_pdf_info(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    __result = Rcpp::wrap(poppler_pdf_info(x, owner_password, user_password));
    return __result;
END_RCPP
}
// poppler_pdf_text
std::vector<std::string> poppler_pdf_text(RawVector x, std::string owner_password, std::string user_password);
RcppExport SEXP pdftools_poppler_pdf_text(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    __result = Rcpp::wrap(poppler_pdf_text(x, owner_password, user_password));
    return __result;
END_RCPP
}
// poppler_pdf_fonts
List poppler_pdf_fonts(RawVector x, std::string owner_password, std::string user_password);
RcppExport SEXP pdftools_poppler_pdf_fonts(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    __result = Rcpp::wrap(poppler_pdf_fonts(x, owner_password, user_password));
    return __result;
END_RCPP
}
// poppler_pdf_files
List poppler_pdf_files(RawVector x, std::string owner_password, std::string user_password);
RcppExport SEXP pdftools_poppler_pdf_files(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    __result = Rcpp::wrap(poppler_pdf_files(x, owner_password, user_password));
    return __result;
END_RCPP
}
// poppler_pdf_toc
List poppler_pdf_toc(RawVector x, std::string owner_password, std::string user_password);
RcppExport SEXP pdftools_poppler_pdf_toc(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    __result = Rcpp::wrap(poppler_pdf_toc(x, owner_password, user_password));
    return __result;
END_RCPP
}
// poppler_render_page
RawVector poppler_render_page(RawVector x, std::string owner_password, std::string user_password, int i);
RcppExport SEXP pdftools_poppler_render_page(SEXP xSEXP, SEXP owner_passwordSEXP, SEXP user_passwordSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type owner_password(owner_passwordSEXP);
    Rcpp::traits::input_parameter< std::string >::type user_password(user_passwordSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    __result = Rcpp::wrap(poppler_render_page(x, owner_password, user_password, i));
    return __result;
END_RCPP
}
