// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// poppler_config
List poppler_config();
RcppExport SEXP pdftools_poppler_config() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(poppler_config());
    return __result;
END_RCPP
}
// poppler_pdf_info
List poppler_pdf_info(RawVector x, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_pdf_info(SEXP xSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_pdf_info(x, opw, upw));
    return __result;
END_RCPP
}
// poppler_pdf_text
std::vector<std::string> poppler_pdf_text(RawVector x, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_pdf_text(SEXP xSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_pdf_text(x, opw, upw));
    return __result;
END_RCPP
}
// poppler_pdf_fonts
List poppler_pdf_fonts(RawVector x, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_pdf_fonts(SEXP xSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_pdf_fonts(x, opw, upw));
    return __result;
END_RCPP
}
// poppler_pdf_files
List poppler_pdf_files(RawVector x, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_pdf_files(SEXP xSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_pdf_files(x, opw, upw));
    return __result;
END_RCPP
}
// poppler_pdf_toc
List poppler_pdf_toc(RawVector x, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_pdf_toc(SEXP xSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_pdf_toc(x, opw, upw));
    return __result;
END_RCPP
}
// poppler_render_page
RawVector poppler_render_page(RawVector x, int pagenum, double dpi, std::string opw, std::string upw);
RcppExport SEXP pdftools_poppler_render_page(SEXP xSEXP, SEXP pagenumSEXP, SEXP dpiSEXP, SEXP opwSEXP, SEXP upwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type pagenum(pagenumSEXP);
    Rcpp::traits::input_parameter< double >::type dpi(dpiSEXP);
    Rcpp::traits::input_parameter< std::string >::type opw(opwSEXP);
    Rcpp::traits::input_parameter< std::string >::type upw(upwSEXP);
    __result = Rcpp::wrap(poppler_render_page(x, pagenum, dpi, opw, upw));
    return __result;
END_RCPP
}
