# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poppler_version <- function() {
    .Call('poppler_poppler_version', PACKAGE = 'poppler')
}

poppler_pdf_info <- function(x, owner_password, user_password) {
    .Call('poppler_poppler_pdf_info', PACKAGE = 'poppler', x, owner_password, user_password)
}

poppler_pdf_text <- function(x, owner_password, user_password) {
    .Call('poppler_poppler_pdf_text', PACKAGE = 'poppler', x, owner_password, user_password)
}

